version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./docs:/app/docs  # For gen scripts in prod; indented under backend
    environment:
      - DEV_MODE=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  redis:  # P3 tease
    image: redis:alpine
    ports:
      - "6379:6379"