version: "3.9"

services:
  db:
    image: timescale/timescaledb:latest-pg16
    container_name: futures-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: futures
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - futuresnet

volumes:
  pgdata:

networks:
  futuresnet:
    driver: bridge
